# Each instruction in this file generates a new layer that gets pushed to your local image cache
# The line below states we will base our new image on the Latest Official Nginx
FROM nginx:latest

# Identify the maintainer of an image
LABEL version="0.0.1"
LABEL maintainer="mankindlatifat.com"

# Update the working directory
WORKDIR /usr/share/nginx/html

# Replace index.html with a custom file
COPY index.html index.html
